### ISSUE TITLE
The split function behaves differently from gawk

### ISSUE THREAD

**Issue by boomker** [linux-china/zawk#6]
The delimiter 'x' in the screenshot has a similar effect to a null character in gawk.

![图片](https://github.com/user-attachments/assets/0399ce79-6197-4195-b1f1-2f0cf0d94702)

```awk
zawk -v NH="你好" 'BEGIN{split(NH,aw,'x');{print aw[2]}}'
```

**Comment by linux-china** [comment]
根据`awk '{split($0, array, ":")}'`，你想表达的是使用`x` 做分割符吗？  

` zawk -v NH="你好" 'BEGIN{split(NH,aw,"x");{print aw[2]}}'  `

**Comment by linux-china** [comment]
如果是这个需求，可以考虑提交一个`chars()`的函数，这样你就可以针对每一个国际化的字符串进行判断啦。

**Comment by boomker** [comment]
> 如果是这个需求，可以考虑提交一个`chars()`的函数，这样你就可以针对每一个国际化的字符串进行判断啦。

对 rust 几乎没接触过的，业余编程选手，所以对这个函数的贡献是有心无力了，希望大佬可以支持，感谢🙏

**Comment by linux-china** [comment]
这个不麻烦的， 我今天添加一下chars() 函数，问题不大。

**Comment by linux-china** [comment]
Please try version 0.5.23
