### ISSUE TITLE
FR:  Support for count function and negative array indexing

### ISSUE THREAD

**Issue by boomker** [linux-china/zawk#7]
希望可以添加如下特性支持：
1. count(text, 's')， 统计特定字符`s`在字符串`text` 里的个数
2. 访问数组元素可以使用负索引

**Comment by linux-china** [comment]
> 1.  count(text,'s') 
这个使用split可以做到吗？ split后的数组大小-1就是个数。 

>2. 访问数组元素可以使用负索引
这个目前没法支持，主要是破坏了AWK的兼容性，AWK不支持负数索引。  你可能需要自己写一个函数来支持这一特性， 如`element_at(arr, -1)`这样。

**Comment by boomker** [comment]
这两个特性主要是为了便利使用，也都可以自己实现。
